const tableNames = require('../../constants/tableNames')


exports.seed = async (knex) => {
  // Deletes ALL existing entries
  await knex(tableNames.language).del();

  await knex(tableNames.language).insert([
    { name: 'Acholi'},
    { name: 'Afrikaans'},
    { name: 'Albanian'},
    { name: 'Amharic'},
    { name: 'Arabic'},
    { name: 'Ashante'},
    { name: 'Assyrian'},
    { name: 'Azerbaijani'},
    { name: 'Azeri'},
    { name: 'Bajuni'},
    { name: 'Basque'},
    { name: 'Behdini'},
    { name: 'Belorussian'},
    { name: 'Bengali'},
    { name: 'Berber'},
    { name: 'Bosnian'},
    { name: 'Bravanese'},
    { name: 'Bulgarian'},
    { name: 'Burmese'},
    { name: 'Cakchiquel'},
    { name: 'Cambodian'},
    { name: 'Cantonese'},
    { name: 'Catalan'},
    { name: 'Chaldean'},
    { name: 'Chamorro'},
    { name: 'Chao-chow'},
    { name: 'Chavacano'},
    { name: 'Chuukese'},
    { name: 'Coptic'},
    { name: 'Croatian'},
    { name: 'Czech'},
    { name: 'Danish'},
    { name: 'Dari'},
    { name: 'Dinka'},
    { name: 'Diula'},
    { name: 'Dutch'},
    { name: 'Egyptian Arabic'},
    { name: 'English'},
    { name: 'Estonian'},
    { name: 'Fante'},
    { name: 'Farsi'},
    { name: 'Finnish'},
    { name: 'Flemish'},
    { name: 'French'},
    { name: 'Fukienese'},
    { name: 'Fula'},
    { name: 'Fulani'},
    { name: 'Fuzhou'},
    { name: 'Gaddang'},
    { name: 'Gaelic'},
    { name: 'Gaelic-irish'},
    { name: 'Gaelic-scottish'},
    { name: 'Georgian'},
    { name: 'German'},
    { name: 'Gorani'},
    { name: 'Greek'},
    { name: 'Gujarati'},
    { name: 'Gulf Arabic'},
    { name: 'Haitian Creole'},
    { name: 'Hakka'},
    { name: 'Hakka-chinese'},
    { name: 'Hausa'},
    { name: 'Hebrew'},
    { name: 'Hindi'},
    { name: 'Hmong'},
    { name: 'Hungarian'},
    { name: 'Ibanag'},
    { name: 'Icelandic'},
    { name: 'Igbo'},
    { name: 'Ilocano'},
    { name: 'Indonesian'},
    { name: 'Inuktitut'},
    { name: 'Italian'},
    { name: 'Jakartanese'},
    { name: 'Japanese'},
    { name: 'Javanese'},
    { name: 'Kanjobal'},
    { name: 'Karen'},
    { name: 'Karenni'},
    { name: 'Kashmiri'},
    { name: 'Kazakh'},
    { name: 'Kikuyu'},
    { name: 'Kinyarwanda'},
    { name: 'Kirundi'},
    { name: 'Korean'},
    { name: 'Kosovan'},
    { name: 'Kotokoli'},
    { name: 'Krio'},
    { name: 'Kurdish'},
    { name: 'Kurmanji'},
    { name: 'Kyrgyz'},
    { name: 'Lakota'},
    { name: 'Laotian'},
    { name: 'Latvian'},
    { name: 'Levantine Arabic'},
    { name: 'Lingala'},
    { name: 'Lithuanian'},
    { name: 'Luganda'},
    { name: 'Maay'},
    { name: 'Macedonian'},
    { name: 'Malay'},
    { name: 'Malayalam'},
    { name: 'Maltese'},
    { name: 'Mandarin'},
    { name: 'Mandingo'},
    { name: 'Mandinka'},
    { name: 'Marathi'},
    { name: 'Marshallese'},
    { name: 'Mirpuri'},
    { name: 'Mixteco'},
    { name: 'Moldavan'},
    { name: 'Mongolian'},
    { name: 'Montenegrin'},
    { name: 'Navajo'},
    { name: 'Neapolitan'},
    { name: 'Nepali'},
    { name: 'Nigerian Pidgin'},
    { name: 'North African Arabic'},
    { name: 'Norwegian'},
    { name: 'Oromo'},
    { name: 'Pahari'},
    { name: 'Papago'},
    { name: 'Papiamento'},
    { name: 'Pashto'},
    { name: 'Patois'},
    { name: 'Pidgin English'},
    { name: 'Polish'},
    { name: 'Portug.creole'},
    { name: 'Portuguese'},
    { name: 'Pothwari'},
    { name: 'Pulaar'},
    { name: 'Punjabi'},
    { name: 'Putian'},
    { name: 'Quichua'},
    { name: 'Romanian'},
    { name: 'Russian'},
    { name: 'Samoan'},
    { name: 'Serbian'},
    { name: 'Shanghainese'},
    { name: 'Shona'},
    { name: 'Sichuan'},
    { name: 'Sicilian'},
    { name: 'Sinhalese'},
    { name: 'Slovak'},
    { name: 'Somali'},
    { name: 'Sorani'},
    { name: 'Spanish'},
    { name: 'Sudanese Arabic'},
    { name: 'Sundanese'},
    { name: 'Susu'},
    { name: 'Swahili'},
    { name: 'Swedish'},
    { name: 'Sylhetti'},
    { name: 'Tagalog'},
    { name: 'Taiwanese'},
    { name: 'Tajik'},
    { name: 'Tamil'},
    { name: 'Telugu'},
    { name: 'Thai'},
    { name: 'Tibetan'},
    { name: 'Tigre'},
    { name: 'Tigrinya'},
    { name: 'Toishanese'},
    { name: 'Tongan'},
    { name: 'Toucouleur'},
    { name: 'Trique'},
    { name: 'Tshiluba'},
    { name: 'Turkish'},
    { name: 'Ukrainian'},
    { name: 'Urdu'},
    { name: 'Uyghur'},
    { name: 'Uzbek'},
    { name: 'Vietnamese'},
    { name: 'Visayan'},
    { name: 'Welsh'},
    { name: 'Wolof'},
    { name: 'Yiddish'},
    { name: 'Yoruba'},
    { name: 'Yupik'},
  ])


};
